---
- name: Add pool for VLAN_20
  community.routeros.command:
    commands:
      - /ip pool add name=pool_20 ranges=192.168.20.10-192.168.20.100

- name: Add pool for VLAN_30
  community.routeros.command:
    commands:
      - /ip pool add name=pool_30 ranges=192.168.30.10-192.168.30.100

- name: Add pool for VLAN_40
  community.routeros.command:
    commands:
      - /ip pool add name=pool_40 ranges=192.168.40.10-192.168.40.100
